### ISSUE TITLE
neuralforecast fails when installed in a python environment alongside old version of transformers

### ISSUE THREAD

**Issue by merrittkowaleski** [Nixtla/neuralforecast#476]
**Description**

This is a rather specific bug, but it's creating some issues when integrating neuralforecast with AutonML/D3M.  Running `import neuralforecast` gives an error under the following conditions:

- The package `transformers` is present in the environment
- Its version is less than 4.6.0 (Have tested on 4.4.2, 4.5.0, 4.5.1, 4.6.0, and 4.7.0)

[Transformers release history](https://pypi.org/project/transformers/#history), for reference.

The error is as follows:
>  \>\>\> import neuralforecast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/neuralforecast/__init__.py", line 3, in <module>
    from .core import NeuralForecast
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/neuralforecast/core.py", line 17, in <module>
    from .tsdataset import TimeSeriesDataset
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/neuralforecast/tsdataset.py", line 11, in <module>
    import pytorch_lightning as pl
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 26, in <module>
    from torchmetrics import Metric
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/torchmetrics/functional/text/__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/torchmetrics/functional/text/bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/transformers/utils/versions.py", line 94, in require_version_core
    return require_version(requirement, hint)
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/transformers/utils/versions.py", line 85, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/mkowales/anaconda3/envs/nftest/lib/python3.8/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

**To Reproduce**

>  \>\>\> conda create -n nftest python=3.8
 \>\>\> conda activate nftest
 \>\>\> pip install neuralforecast
 \>\>\> pip install transformers==4.5.1
 \>\>\> python -c ‘import neuralforecast’

 - OS: Springdale Open Enterprise Linux
 - Version: 8.6 (Modena)

**Potential Solutions**

It's very possible that this is an issue with `transformers` rather than `neuralforecast`, in which case I'll submit this bug report to the author(s) of `transformers`.  In that case, the interim solution might be to change the requirements of `neuralforecast` (although I'm not sure if it's possible to specify a requirement like "this package does not need to be present but if it is it must be over a certain version").

**Comment by sammiller06** [comment]
Bumping this up too for attention.

pip install seems to get the wrong version of pytorch-lightning. It's installing 1.6.5, rather than 1.9+

**Comment by kdgutier** [comment]
Hi @merrittkowaleski, 

We did a quick fix to NeuralForecast installation instructions here
- https://github.com/Nixtla/neuralforecast/blob/main/environment.yml

It is now installing Pytorch Lightning 1.9.0 instead of 1.6.0
From what you mentioned in the transformers package they are also using PL as dependency which might be a collision.

Would you be able to confirm if this installation solves the problem?
!pip install git+https://github.com/Nixtla/neuralforecast.git

If that solves the issue we need to update the pypi to include the installation fix

**Comment by FedericoGarza** [comment]
hey @merrittkowaleski! I noticed that there was a problem with the dependencies of the `transformers` library,  it has been resolved as of version `4.6.0`. [Here](https://github.com/huggingface/transformers/issues/20799) is a thread on the topic. I just wanted to ask if there was a specific reason you wanted to use version `v4.5.1`? If there is anything I can do to help, please let me know. :)

**Comment by FedericoGarza** [comment]
hey @sammiller06! Sorry for the inconvenience. We updated the library to make it compatible with `torch`, and `ligthning>=2`. The changes have already been incorporated into the main branch, feel free to give it a test run! :). We'll be releasing the new version soon!🙌

**Comment by merrittkowaleski** [comment]
@kdgutier I replied to this via email, but I'll say it here too so that everyone in this thread can see it: I tested with the new version of `neuralforecast`, but the issue was still present.

@FedericoGarza I appreciate the help!  I'm working on a project that uses both `neuralforecast` and `sri-d3m`, which requires `transformers==4.5.1`.  However, there's a good chance the requirement of a specific version is needlessly strict--that's been an issue with other similar packages.   Additionally, the part of `sri-d3m` that relies on `transformers` is not currently used. So, this is a less pressing issue than I initially thought, and can probably be resolved by changing the requirements of `sri-d3m`.
