### ISSUE TITLE
Broken tutorial LongHorizon_with_NHITS

### ISSUE THREAD

**Issue by kivimike** [Nixtla/neuralforecast#525]
When I run the notebook using colab and get to cross validation cell I get: 
```RuntimeError: No best trial found for the given metric: loss. This means that no trial has reported this metric, or all values reported for this metric are NaN. To not ignore NaN values, you can set the `filter_nan_and_inf` arg to False.```
At first I thought this happens because loss is not specified in code (only mentioned in markdown cell), but when i try loss : 
```models = [AutoNHITS(h=horizon, config=nhits_config, num_samples=5, loss=DistributionLoss(distribution='StudentT', level=[80,90]))]```, I still get the mentioned exception.
To reproduce:
- simply run the example notebook until this cell: 
```
%%capture
fcst = NeuralForecast(
    models=models,
    freq='15min')

fcst_df = fcst.cross_validation(df=Y_df, val_size=val_size,
                                test_size=test_size, n_windows=None)
```

**Comment by kivimike** [comment]
Actually the same exception is thrown when you call fit method for the first time in Getting_Started_complete notebook.

**Comment by soutrik7771** [comment]
Facing the same issue , kindly look into issue no 53. I have posted the entire trace

**Comment by soutrik7771** [comment]
https://github.com/Nixtla/neuralforecast/issues/526

**Comment by kivimike** [comment]
fixed installing from the main branch. https://github.com/Nixtla/neuralforecast/issues/526#issuecomment-1512154870
still, you need to fix the notebook, because there is no loss function to optimize

**Comment by DKorman** [comment]
Hi guys, tnx for the effort! For me installing from the main branch does not solve this issue. I haven't pinned any versions of torch lib though.

**Comment by kdgutier** [comment]
Hey @DKorman,

We just released last week a correction to NeuralForecast pip and conda pytorch and pytorch-lightning dependencies.
Have you solved your installation problem?

**Comment by jz8-armohb** [comment]
> fixed by installing from the main branch. [#526 (comment)](https://github.com/Nixtla/neuralforecast/issues/526#issuecomment-1512154870)
> still, you need to fix the notebook, because there is no loss function to optimize

@kivimike How to fix the code, may I ask?
Actually I've tried commented `AutoLSTM(h=48, loss=MQLoss(), num_samples=2)` aka only leave the `AutoNHITS` part and the `nf.fit` part run correctly. However if I add `AutoLSTM` part back, the error message `RuntimeError: No best trial found for the given metric: loss. This means that no trial has reported this metric, or all values reported for this metric are NaN. To not ignore NaN values, you can set the filter_nan_and_inf arg to False.` popped out again.

**Comment by jz8-armohb** [comment]
Hi @DKorman

Really strange. I created a fresh new virtual env  with python 3.10 and re-installed the corresponding packages:
```shell
conda create -n nf_pip python=3.10 
conda activate nf_pip
pip install jupyter
pip install neuralforecast "torch<2.0.0"
pip install matplotlib hyperopt pyarrow fastparquet statsforecast datasetsforecast
```
and I correctly finished running code of EVERY block in `Getting_Started_complete.ipynb`

All the packages I installed in this virtual envirionments are listd below:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
adagio                    0.2.4                    pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
ansi2html                 1.8.0                    pypi_0    pypi
antlr4-python3-runtime    4.11.1                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
blinker                   1.6.2                    pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
cachetools                5.3.0                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cramjam                   2.6.2                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dash                      2.9.3                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
datasetsforecast          0.0.8                    pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
fastparquet               2023.4.0                 pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
flask                     2.3.2                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fs                        2.4.16                   pypi_0    pypi
fsspec                    2023.5.0                 pypi_0    pypi
fugue                     0.8.3                    pypi_0    pypi
fugue-sql-antlr           0.1.6                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
google-auth               2.18.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
hyperopt                  0.2.7                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
ipykernel                 6.23.0                   pypi_0    pypi
ipython                   8.13.2                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.6                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyter-dash              0.4.2                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.5.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.7                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
llvmlite                  0.40.0                   pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
msgpack                   1.0.5                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.4.0                    pypi_0    pypi
nbformat                  5.8.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
neuralforecast            1.4.0                    pypi_0    pypi
notebook                  6.5.4                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numba                     0.57.0                   pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
orjson                    3.8.12                   pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1          py310h06a4308_0  
platformdirs              3.5.0                    pypi_0    pypi
plotly                    5.14.1                   pypi_0    pypi
plotly-resampler          0.8.3.2                  pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py4j                      0.10.9.7                 pypi_0    pypi
pyarrow                   12.0.0                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.10.11              h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytorch-lightning         1.6.5                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qpd                       0.4.1                    pypi_0    pypi
qtconsole                 5.4.3                    pypi_0    pypi
qtpy                      2.3.1                    pypi_0    pypi
ray                       2.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.30.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
setuptools                66.0.0          py310h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlglot                   12.2.1                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.2                    pypi_0    pypi
statsforecast             1.5.0                    pypi_0    pypi
statsmodels               0.14.0                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.6                      pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     1.13.1                   pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
tornado                   6.3.1                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
trace-updater             0.0.9.1                  pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
triad                     0.8.7                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
virtualenv                20.23.0                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.38.4          py310h06a4308_0  
widgetsnbextension        4.0.7                    pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yarl                      1.9.2                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
```

**Comment by cchallu** [comment]
This issue should be fixed with the new PyTorch Lightning and Tune versions.
